name: FR_test_11_actions

on:
  # Trigger the workflow on push to the 'main' branch
  push:
    branches:
      - main

  # Trigger the workflow on a pull request targeting the 'main' branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.8.0'

      # Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: TDD_lektion_4_Frontend_Jest_Test/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('TDD_lektion_4_Frontend_Jest_Test/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: TDD_lektion_4_Frontend_Jest_Test

      # Run tests
      - name: Run tests
        run: npm test
        working-directory: TDD_lektion_4_Frontend_Jest_Test
