name: FR_test_11_actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.8.0'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: TDD_lektion_4_Frontend_Jest_Test/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('TDD_lektion_4_Frontend_Jest_Test/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install
        working-directory: TDD_lektion_4_Frontend_Jest_Test

      - name: Run tests
        run: npm test
        working-directory: TDD_lektion_4_Frontend_Jest_Test
